name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün gece 12'de çalıştır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: FerhatAkkopru
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4  # V4 sürümünü kullanıyoruz
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
